### ISSUE TITLE
/dev/sdc is sometimes mounted

### ISSUE THREAD

**Issue by Seb35** [azediv/gnadi-coreos#2] opened 2017-06-06 07:44 UTC
First, thanks a lot for this recipe! it helps me great in setting up a Gandi VM for testing CoreOS.

I experienced a small issue in the coreos-install script on the line `ROOT_DEV=$(blkid -t "LABEL=ROOT" -o device "${DEVICE}"*)` returning the error code `2`. When I executed `install-core.sh` up to the remote setup and stopped it (properly with `exit`) before the `gandi vm stop`, and I connected through SSH to the VM, I saw `/dev/sdc` was still mounted. When I unmount it and relaunch `coreos-install`, it works.

I cannot say for sure there is a correlation between the still-mounted `/dev/sdc` and the error (I tried about 6-8 times with various debug scenarios) but it would be worth investigating more about it.

I tried to move the `umount /dev/sdc` later in `install-core.sh`, just before the `coreos-install` (e.g. if apt-get does something about it), but without success. So not sure about a resolution path.

**Comment by Seb35** [comment] 2017-06-06 07:45
I tried also to add a `apt-get dist-upgrade -y` but it didn’t help.

**Comment by azediv** [comment] 2017-06-12 14:37
hello, thanks for your feedback :)

issue was reproduce and root cause is data disk management by Gandi agent, specifically due to this value : CONFIG_ALLOW_MOUNT=1 in /etc/default/gandi

I've add a branch with a new version of the script :
now use FR-SD3 datacenter, 
xvdb partition for data disk  
change value from 1 to 0 for CONFIG_ALLOW_MOUNT

If you want to try here's a direct link to latest raw version of script : 

https://raw.githubusercontent.com/azediv/gnadi-coreos/reread_partitions/install-core.sh

does it solve issue on your test too ? Thx !

**Comment by azediv** [comment] 2017-07-08 11:09
merged in master

**Closed as completed by azediv** 2017-07-08 11:09 UTC
